
# Custom CMake module for finding "NVIDIA PhysX Toolkit" files

set(PHYSX_SDK_DEFAULT_PATH $ENV{PROGRAMFILES}/NVIDIA Corporation/NVIDIA PhysX SDK)
set(
	PHYSX_SDK_DEFAULT_LIB_PATHS
	${PHYSX_SDK_DEFAULT_PATH}/v3.0/Lib/win32
	${PHYSX_SDK_DEFAULT_PATH}/v3.1/Lib/win32
	${PHYSX_SDK_DEFAULT_PATH}/v3.2/Lib/win32
)

find_path(
	PHYSX_INCLUDE_DIR
	PxPhysicsAPI.h
	PATHS
	${PHYSX_SDK_DEFAULT_PATH}/v3.0/Include
	${PHYSX_SDK_DEFAULT_PATH}/v3.1/Include
	${PHYSX_SDK_DEFAULT_PATH}/v3.2/Include
)

find_library(
	PHYSX_LIBRARY
	NAMES PhysX3_x86 PhysX3_x64 PhysX3
	PATHS ${PHYSX_SDK_DEFAULT_LIB_PATHS}
)

find_library(
	PHYSX_COMMON_LIBRARY
	NAMES PhysX3Common_x86 PhysX3Common_x64 PhysX3Common
	PATHS ${PHYSX_SDK_DEFAULT_LIB_PATHS}
)

find_library(
	PHYSX_COOKING_LIBRARY
	NAMES PhysX3Cooking_x86 PhysX3Cooking_x64 PhysX3Cooking
	PATHS ${PHYSX_SDK_DEFAULT_LIB_PATHS}
)

find_library(
	PHYSX_PROFILE_SDK_LIBRARY
	NAMES PhysXProfileSDK_x86 PhysXProfileSDK_x64 PhysXProfileSDK
	PATHS ${PHYSX_SDK_DEFAULT_LIB_PATHS}
)

find_library(
	PHYSX_EX_LIBRARY
	NAMES PhysX3Extensions_x86 PhysX3Extensions_x64 PhysX3Extensions
	PATHS ${PHYSX_SDK_DEFAULT_LIB_PATHS}
)

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(
	PHYSX
	DEFAULT_MSG
	PHYSX_LIBRARY PHYSX_COMMON_LIBRARY PHYSX_COOKING_LIBRARY PHYSX_PROFILE_SDK_LIBRARY PHYSX_EX_LIBRARY
	PHYSX_INCLUDE_DIR
)

mark_as_advanced(PHYSX_LIBRARY PHYSX_COMMON_LIBRARY PHYSX_COOKING_LIBRARY PHYSX_PROFILE_SDK_LIBRARY PHYSX_EX_LIBRARY PHYSX_INCLUDE_DIR)
