"/*\n"
" * D3D11 default primitive drawing shader file\n"
" * \n"
" * This file is part of the \"SoftPixel Engine\" (Copyright (c) 2008 by Lukas Hermanns)\n"
" * See \"SoftPixelEngine.hpp\" for license information.\n"
" */\n"
"#define MAX_NUM_VERTICES 8\n"
"struct SVertex\n"
"{\n"
" float4 Position;\n"
" float4 Color;\n"
"};\n"
"cbuffer BufferVS : register(b0)\n"
"{\n"
"    float4x4 WVPMatrix; //!< World-view-projection matrix.\n"
" SVertex Vertices[MAX_NUM_VERTICES];\n"
"};\n"
"struct SVertexInput\n"
"{\n"
" uint Id : SV_VertexID;\n"
"};\n"
"struct SVertexOutput\n"
"{\n"
"    float4 Position : SV_Position;\n"
"    float4 Color : COLOR0;\n"
"};\n"
"SVertexOutput VertexMain(SVertexInput In)\n"
"{\n"
"    SVertexOutput Out = (SVertexOutput)0;\n"
"    // Process vertex coordinate\n"
" SVertex Vert = Vertices[In.Id];\n"
" Out.Position = mul(WVPMatrix, Vert.Position);\n"
"    Out.Color  = Vert.Color;\n"
"    return Out;\n"
"}\n"
"float4 PixelMain(SVertexOutput In) : SV_Target0\n"
"{\n"
"    return In.Color;\n"
"}\n"
