"/*\n"
" * GLSL shader core file\n"
" * \n"
" * This file is part of the \"SoftPixel Engine\" (Copyright (c) 2008 by Lukas Hermanns)\n"
" * See \"SoftPixelEngine.hpp\" for license information.\n"
" */\n"
"\n"
"#define float2                    vec2\n"
"#define float3                    vec3\n"
"#define float4                    vec4\n"
"\n"
"#define float2x2                mat2\n"
"#define float3x3                mat3\n"
"#define float4x4                mat4\n"
"\n"
"#define MUL(m, v)                (m) * (v)\n"
"#define MUL_TRANSPOSED(v, m)    transpose(m) * (v)\n"
"#define CAST(t, v)                t(v)\n"
"#define MUL_NORMAL(n)            (n).xyz = float3x3(Tangent, Binormal, Normal) * (n).xyz\n"
"\n"
"#define saturate(v)                clamp(v, 0.0, 1.0)\n"
"#define clip(v)                    if (v < 0.0) { discard; }\n"
"\n"
"#define tex2D                    texture2D\n"
"#define tex2Dgrad                texture2DGradARB\n"
"#define tex2DArrayLod(s, t)        texture2DArrayLod(s, (t).xyz, (t).w)\n"
"#define tex2DArray(s, t)        texture2DArray(s, t)\n"
"#define tex2DGrad(s, t, x, y)    texture2DGradARB(s, t, x, y)\n"
"#define ddx                        dFdx\n"
"#define ddy                        dFdy\n"
