"/*\n"
" * HLSL shader core file\n"
" * \n"
" * This file is part of the \"SoftPixel Engine\" (Copyright (c) 2008 by Lukas Hermanns)\n"
" * See \"SoftPixelEngine.hpp\" for license information.\n"
" */\n"
"\n"
"#define MUL(m, v)                mul(m, v)\n"
"#define MUL_TRANSPOSED(v, m)    mul(v, m)\n"
"#define CAST(t, v)                ((t)(v))\n"
"\n"
"#define tex2DArrayLod(s, t)        tex2Dlod(s, t)\n"
"#define tex2DGrad(s, t, x, y)    tex2Dgrad(s, t, x, y)\n"
