/*
 * Sound effect interface header
 * 
 * This file is part of the "SoftPixel Engine" (Copyright (c) 2008 by Lukas Hermanns)
 * See "SoftPixelEngine.hpp" for license information.
 */

#ifndef __SP_AUDIO_SOUNDEFFECT_H__
#define __SP_AUDIO_SOUNDEFFECT_H__


#include "Base/spStandard.hpp"


namespace sp
{
namespace audio
{


//! Sound effect types.
enum ESoundEffectTypes
{
    SOUNDEFFECT_REVERBERATION = 0,  //!< Reverberation sound effect. Used for sound reflections.
    SOUNDEFFECT_CHORUS,             //!< Not yet supported.
    SOUNDEFFECT_DISTORTION,         //!< Not yet supported.
    SOUNDEFFECT_ECHO,               //!< Not yet supported.
    SOUNDEFFECT_FLANGER,            //!< Not yet supported.
    SOUNDEFFECT_FREQUENCY_SHIFTER,  //!< Not yet supported.
    SOUNDEFFECT_VOCAL_MORPHER,      //!< Not yet supported.
    SOUNDEFFECT_PITCH_SHIFTER,      //!< Not yet supported.
    SOUNDEFFECT_RING_MODULATOR,     //!< Not yet supported.
    SOUNDEFFECT_AUTOWAH,            //!< Not yet supported.
    SOUNDEFFECT_COMPRESSOR,         //!< Not yet supported.
    SOUNDEFFECT_EQUALIZER,          //!< Not yet supported.
};

/**
Sound effect presets.
\note All these presets have been taken from the "EFX-Util.h" file which is part of the "OpenAL EFX" extension.
*/
enum ESoundEffectPresets
{
    /* Reverberation default presets: */
    SFXPRESET_REVERB_GENERIC = 0,
    SFXPRESET_REVERB_PADDEDCELL,
    SFXPRESET_REVERB_ROOM,
    SFXPRESET_REVERB_BATHROOM,
    SFXPRESET_REVERB_LIVINGROOM,
    SFXPRESET_REVERB_STONEROOM,
    SFXPRESET_REVERB_AUDITORIUM,
    SFXPRESET_REVERB_CONCERTHALL,
    SFXPRESET_REVERB_CAVE,
    SFXPRESET_REVERB_ARENA,
    SFXPRESET_REVERB_HANGAR,
    SFXPRESET_REVERB_CARPETTEDHALLWAY,
    SFXPRESET_REVERB_HALLWAY,
    SFXPRESET_REVERB_STONECORRIDOR,
    SFXPRESET_REVERB_ALLEY,
    SFXPRESET_REVERB_FOREST,
    SFXPRESET_REVERB_CITY,
    SFXPRESET_REVERB_MOUNTAINS,
    SFXPRESET_REVERB_QUARRY,
    SFXPRESET_REVERB_PLAIN,
    SFXPRESET_REVERB_PARKINGLOT,
    SFXPRESET_REVERB_SEWERPIPE,
    SFXPRESET_REVERB_UNDERWATER,
    SFXPRESET_REVERB_DRUGGED,
    SFXPRESET_REVERB_DIZZY,
    SFXPRESET_REVERB_PSYCHOTIC,
    
    /* Reverberation castle presets: */
    SFXPRESET_REVERB_CASTLE_SMALLROOM,
    SFXPRESET_REVERB_CASTLE_SHORTPASSAGE,
    SFXPRESET_REVERB_CASTLE_MEDIUMROOM,
    SFXPRESET_REVERB_CASTLE_LONGPASSAGE,
    SFXPRESET_REVERB_CASTLE_LARGEROOM,
    SFXPRESET_REVERB_CASTLE_HALL,
    SFXPRESET_REVERB_CASTLE_CUPBOARD,
    SFXPRESET_REVERB_CASTLE_COURTYARD,
    SFXPRESET_REVERB_CASTLE_ALCOVE,
    
    /* Reverberation factory presets: */
    SFXPRESET_REVERB_FACTORY_ALCOVE,
    SFXPRESET_REVERB_FACTORY_SHORTPASSAGE,
    SFXPRESET_REVERB_FACTORY_MEDIUMROOM,
    SFXPRESET_REVERB_FACTORY_LONGPASSAGE,
    SFXPRESET_REVERB_FACTORY_LARGEROOM,
    SFXPRESET_REVERB_FACTORY_HALL,
    SFXPRESET_REVERB_FACTORY_CUPBOARD,
    SFXPRESET_REVERB_FACTORY_COURTYARD,
    SFXPRESET_REVERB_FACTORY_SMALLROOM,
    
    /* Reverberation icepalace presets: */
    SFXPRESET_REVERB_ICEPALACE_ALCOVE,
    SFXPRESET_REVERB_ICEPALACE_SHORTPASSAGE,
    SFXPRESET_REVERB_ICEPALACE_MEDIUMROOM,
    SFXPRESET_REVERB_ICEPALACE_LONGPASSAGE,
    SFXPRESET_REVERB_ICEPALACE_LARGEROOM,
    SFXPRESET_REVERB_ICEPALACE_HALL,
    SFXPRESET_REVERB_ICEPALACE_CUPBOARD,
    SFXPRESET_REVERB_ICEPALACE_COURTYARD,
    SFXPRESET_REVERB_ICEPALACE_SMALLROOM,
    
    /* Reverberation spacestation presets: */
    SFXPRESET_REVERB_SPACESTATION_ALCOVE,
    SFXPRESET_REVERB_SPACESTATION_MEDIUMROOM,
    SFXPRESET_REVERB_SPACESTATION_SHORTPASSAGE,
    SFXPRESET_REVERB_SPACESTATION_LONGPASSAGE,
    SFXPRESET_REVERB_SPACESTATION_LARGEROOM,
    SFXPRESET_REVERB_SPACESTATION_HALL,
    SFXPRESET_REVERB_SPACESTATION_CUPBOARD,
    SFXPRESET_REVERB_SPACESTATION_SMALLROOM,
    
    /* Reverberation wooden presets: */
    SFXPRESET_REVERB_WOODEN_ALCOVE,
    SFXPRESET_REVERB_WOODEN_SHORTPASSAGE,
    SFXPRESET_REVERB_WOODEN_MEDIUMROOM,
    SFXPRESET_REVERB_WOODEN_LONGPASSAGE,
    SFXPRESET_REVERB_WOODEN_LARGEROOM,
    SFXPRESET_REVERB_WOODEN_HALL,
    SFXPRESET_REVERB_WOODEN_CUPBOARD,
    SFXPRESET_REVERB_WOODEN_SMALLROOM,
    SFXPRESET_REVERB_WOODEN_COURTYARD,
    
    /* Reverberation sport presets: */
    SFXPRESET_REVERB_SPORT_EMPTYSTADIUM,
    SFXPRESET_REVERB_SPORT_SQUASHCOURT,
    SFXPRESET_REVERB_SPORT_SMALLSWIMMINGPOOL,
    SFXPRESET_REVERB_SPORT_LARGESWIMMINGPOOL,
    SFXPRESET_REVERB_SPORT_GYMNASIUM,
    SFXPRESET_REVERB_SPORT_FULLSTADIUM,
    SFXPRESET_REVERB_SPORT_STADIUMTANNOY,
    
    /* Reverberation prefab presets: */
    SFXPRESET_REVERB_PREFAB_WORKSHOP,
    SFXPRESET_REVERB_PREFAB_SCHOOLROOM,
    SFXPRESET_REVERB_PREFAB_PRACTISEROOM,
    SFXPRESET_REVERB_PREFAB_OUTHOUSE,
    SFXPRESET_REVERB_PREFAB_CARAVAN,
    
    /* Reverberation dome- and pipe presets: */
    SFXPRESET_REVERB_DOME_TOMB,
    SFXPRESET_REVERB_PIPE_SMALL,
    SFXPRESET_REVERB_DOME_SAINTPAULS,
    SFXPRESET_REVERB_PIPE_LONGTHIN,
    SFXPRESET_REVERB_PIPE_LARGE,
    SFXPRESET_REVERB_PIPE_RESONANT,
    
    /* Reverberation outdoor presets: */
    SFXPRESET_REVERB_OUTDOORS_BACKYARD,
    SFXPRESET_REVERB_OUTDOORS_ROLLINGPLAINS,
    SFXPRESET_REVERB_OUTDOORS_DEEPCANYON,
    SFXPRESET_REVERB_OUTDOORS_CREEK,
    SFXPRESET_REVERB_OUTDOORS_VALLEY,
    
    /* Reverberation mood presets: */
    SFXPRESET_REVERB_MOOD_HEAVEN,
    SFXPRESET_REVERB_MOOD_HELL,
    SFXPRESET_REVERB_MOOD_MEMORY,
    
    /* Reverberation driving presets: */
    SFXPRESET_REVERB_DRIVING_COMMENTATOR,
    SFXPRESET_REVERB_DRIVING_PITGARAGE,
    SFXPRESET_REVERB_DRIVING_INCAR_RACER,
    SFXPRESET_REVERB_DRIVING_INCAR_SPORTS,
    SFXPRESET_REVERB_DRIVING_INCAR_LUXURY,
    SFXPRESET_REVERB_DRIVING_FULLGRANDSTAND,
    SFXPRESET_REVERB_DRIVING_EMPTYGRANDSTAND,
    SFXPRESET_REVERB_DRIVING_TUNNEL,
    
    /* Reverberation city presets: */
    SFXPRESET_REVERB_CITY_STREETS,
    SFXPRESET_REVERB_CITY_SUBWAY,
    SFXPRESET_REVERB_CITY_MUSEUM,
    SFXPRESET_REVERB_CITY_LIBRARY,
    SFXPRESET_REVERB_CITY_UNDERPASS,
    SFXPRESET_REVERB_CITY_ABANDONED,
    
    /* Reverberation other presets: */
    SFXPRESET_REVERB_DUSTYROOM,
    SFXPRESET_REVERB_CHAPEL,
    SFXPRESET_REVERB_SMALLWATERROOM,
};


//! Sound effect base class. Currently only supported for OpenAL.
class SP_EXPORT SoundEffect
{
    
    public:
        
        SoundEffect();
        virtual ~SoundEffect();
        
        /* Functions */
        
        virtual void setType(const ESoundEffectTypes Type);
        
        virtual void setupEffectPreset(const ESoundEffectPresets Preset);
        
        /* Inline functions */
        
        inline ESoundEffectTypes getType() const
        {
            return Type_;
        }
        
    protected:
        
        /* Members */
        
        ESoundEffectTypes Type_;
        
};


} // /namespace audio

} // /namespace sp


#endif



// ================================================================================
